In [19]:
import pandas as pd
pd.set_option('display.max_columns', None)

data = pd.read_csv("data/countypres_2000-2016.csv")
data = data.drop(["state", "FIPS", "office", "candidate", "version"], axis=1)
data = data.dropna()
data = data[data["year"] == 2016]
#data = data[data["party"] in ["democrat", "republican"]]
data["county state"] = data["county"] + ", " + data["state_po"]

,year,state_po,county,party,candidatevotes,totalvotes,county state
42340,2016,GA,Cobb,democrat,160121.0,330819,"Cobb, GA"
42341,2016,GA,Cobb,republican,152912.0,330819,"Cobb, GA"

In [21]:
dataGroup = data.groupby("county state")
dataGroup.count()

                     year  state_po  county  party  candidatevotes  totalvotes
county state
Abbeville, SC           2         2       2      2               2           2
Acadia, LA              2         2       2      2               2           2
Accomack, VA            2         2       2      2               2           2
Ada, ID                 2         2       2      2               2           2
Adair, IA               2         2       2      2               2           2
Adair, KY               2         2       2      2               2           2
Adair, MO               2         2       2      2               2           2
Adair, OK               2         2       2      2               2           2
Adams, CO               2         2       2      2               2           2
Adams, IA               2         2       2      2               2           2
Adams, ID               2         2       2      2               2           2
Adams, IL               2         2       2      2               2           2
Adams, IN               2         2       2      2               2           2
Adams, MS               2         2       2      2               2           2
Adams, ND               2         2       2      2               2           2
Adams, NE               2         2       2      2               2           2
Adams, OH               2         2       2      2               2           2
Adams, PA               2         2       2      2               2           2
Adams, WA               2         2       2      2               2           2
Adams, WI               2         2       2      2               2           2
Addison, VT             2         2       2      2               2           2
Aiken, SC               2         2       2      2               2           2
Aitkin, MN              2         2       2      2               2           2
Alachua, FL             2         2       2      2               2           2
Alamance, NC            2         2       2      2               2           2
Alameda, CA             2         2       2      2               2           2
Alamosa, CO             2         2       2      2               2           2
Albany, NY              2         2       2      2               2           2
Albany, WY              2         2       2      2               2           2
Albemarle, VA           2         2       2      2               2           2
...                   ...       ...     ...    ...             ...         ...
Wyoming, NY             2         2       2      2               2           2
Wyoming, PA             2         2       2      2               2           2
Wyoming, WV             2         2       2      2               2           2
Wythe, VA               2         2       2      2               2           2
Yadkin, NC              2         2       2      2               2           2
Yakima, WA              2         2       2      2               2           2
Yalobusha, MS           2         2       2      2               2           2
Yamhill, OR             2         2       2      2               2           2
Yancey, NC              2         2       2      2               2           2
Yankton, SD             2         2       2      2               2           2
Yates, NY               2         2       2      2               2           2
Yavapai, AZ             2         2       2      2               2           2
Yazoo, MS               2         2       2      2               2           2
Yell, AR                2         2       2      2               2           2
Yellow Medicine, MN     2         2       2      2               2           2
Yellowstone, MT         2         2       2      2               2           2
Yoakum, TX              2         2       2      2               2           2
Yolo, CA                2         2       2      2               2           2
York, ME                2         2       2      2               2           2
York, NE                2         2       2      2               2           2
York, PA                2         2       2      2               2           2
York, SC                2         2       2      2               2           2
York, VA                2         2       2      2               2           2
Young, TX               2         2       2      2               2           2
Yuba, CA                2         2       2      2               2           2
Yuma, AZ                2         2       2      2               2           2
Yuma, CO                2         2       2      2               2           2
Zapata, TX              2         2       2      2               2           2
Zavala, TX              2         2       2      2               2           2
Ziebach, SD             2         2       2      2               2           2

[3149 rows x 6 columns]